### ISSUE TITLE
why tf.nn.separable_conv2d? Is tf.nn.depthwise_conv2d ok?

### ISSUE THREAD

**Issue by clks-wzz** [ohadlights/mobilenetv2#1]
I found that you use tf.nn.separable_conv2d for depthwise conv. Maybe tf.nn.depthwise_conv2d  more simple?

**Comment by ohadlights** [comment]
Well... I didn't know that this method exists. I'm using slim API (which I like...) and not tf.nn.
Anyway, I don't think it makes any difference.

**Comment by clks-wzz** [comment]
@ohadlights 'separable_conv2d' can group depthwise_conv and pointwise_conv together, as the original paper mentioned. May this op save memory for inference(forward)? Of course, it can't control the activation_function after both sub operations.
Otherwise, your code is very simple and good! \(^o^)/

**Comment by ohadlights** [comment]
thanks. enjoy the net
